disallowed-types = [
    # prefer hashbrown
    "std::collections::HashMap",
    "std::collections::HashSet",
]

disallowed-macros = [
    # only allowed in main.rs
    "std::print",
    "std::println",
    # use log crate instead
    "std::eprint",
    "std::eprintln",
]

type-complexity-threshold = 350
